### PR TITLE
support syslog support for logging and combined log format

### PR DESCRIPTION
**Pull request by makocchi-git**
* now supports `log_file = syslog` in config
* now supports `log_format` in config (add combined format)
* set `None` to stdout and stderr value in DaemonContext
* more detailed description in config file

### CODE REVIEW

**Comment by JumpeiArashi** [comment]
@makocchi-git 
And I'll merge this pull request for a minute. I'll revise above issues.

**Comment by makocchi-git** [comment]
ok, thanks

**Comment by JumpeiArashi** [comment]
My pleasure!

**Comment by makocchi-git** [comment]
BTW, I think that we also should be supporting `log_level = none` for suppress all log.
`logging.handlers.NullHandler` is sutable but `NullHandler` is not available in python 2.6.

**Pull request merged**
