### PR TITLE
Upgrade configobj 5.x in only setup.py

### PR DESCRIPTION
**Pull request by JumpeiArashi**
- [x] Integrate interface for configobj 5.X
- [x] Rewrite all unite test
    + validation
    + loading
    + convert string to config object
    + convert file to config object

### CODE REVIEW

**Comment by JumpeiArashi** [comment]
test this please

**Comment by makocchi-git** [comment]
OK, I will check ASAP

**Comment by JumpeiArashi** [comment]
Oh, thanks(but you don't need see **ASAP**. be more slowly...). I'll push many number of commits. So you looks little by little.
When taking `[WIP]`!

**Comment by JumpeiArashi** [comment]
@makocchi-git 
Gotcha all unit tests are passed:metal: My this time PR is decent large...
But unit tests other than new unit tests are pretty changes. Please please check!

**Comment by makocchi-git** [comment]
[LGTM](http://lgtm.in/i/6bUp8PEoq)

**Pull request merged**
